# .streamlit/secrets.toml

public_gsheets_url = "https://docs.google.com/spreadsheets/d/1Lx3Vv3otWSvUCoibIT54yuWSaQy18tDjT5dUXVn-YgU/edit?usp=sharing"
public_gsheet_csv ="https://docs.google.com/spreadsheets/d/e/2PACX-1vRU-C1LH4s5zE941wzIdN8UL2T5PsfhB6xyDpPQbfodzPcuXmte7VcrRHHUjYSwYdLlLv3CxUpkouZ0/pub?output=csv"